### PR TITLE
lexer.ts: char lookup, fixed indentation, negative&decimal numbers

### PR DESCRIPTION
**Pull request by Symmettry**

### CODE REVIEW

**Comment by Symmettry** [comment]
whoops, it's not working, one moment i need to find out what's wrong

**Comment by Symmettry** [comment]
Alright I fixed it; I accidentally put a break in the wrong spot making it instantly exit the parse loop (and I forgot a break after the case "=").

**Comment by face-hh** [comment]
I will merge this in the next version (when I have time)

**Comment by Symmettry** [comment]
Alright, I also added negative and decimal numbers for it, since it was only a few changes. (Unless you wanted it by design to not have those?)

**Pull request merged**
