### PR TITLE
Added a new showcase

### PR DESCRIPTION
**Pull request by mauro-balades**

### CODE REVIEW

**Comment by Symmettry** [comment]
?

**Comment by mauro-balades** [comment]
it's just a simple game lol

**Comment by face-hh** [comment]
Not sure if you're aware, but your pull request doesn't include any showcase BSX file.

It makes Git ignore the showcase folder.

**Comment by mauro-balades** [comment]
I see, just realised

**Comment by face-hh** [comment]
Sorry, but this is pretty simple to be shown in the showcase.

Feel free to share it in the Discord server (#bussin-x) though!

**Comment by mauro-balades** [comment]
Haha alr

**Pull request closed without merging**
