### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by Polygons1**

### CODE REVIEW

**Comment by Polygons1** [comment]
> My man 1k new lines and 4.4k removed lines, all commits without a proper description and the pr is named "Some changes" how do you expect this to be merged 💀💀💀💀💀💀💀

it's QOL

**Comment by Polygons1** [comment]
btw when @face-hh is gonna marge this?

**Comment by danriedl** [comment]
Lil bro needs some git training fr no cap 🚫 🧢

**Comment by Polygons1** [comment]
> Lil bro needs some git training fr no cap 🚫 🧢

:skull:

**Comment by Polygons1** [comment]
<@778518819055861761> <@778518819055861761> <@778518819055861761> <@778518819055861761> <@778518819055861761> <@778518819055861761> <@778518819055861761> <@778518819055861761> <@778518819055861761> <@778518819055861761> <@778518819055861761> <@778518819055861761>

**Comment by Polygons1** [comment]
@face-hh if you want, I will make an HTTP request to get the local currency

**Comment by Polygons1** [comment]
<@778518819055861761> go back to <#907306705090646066> 😂

**Comment by Polygons1** [comment]
@everyone and <@778518819055861761>, I did it!

**Comment by tovade** [comment]
there's a thing called ts-node btw

**Comment by Polygons1** [comment]
> there's a thing called ts-node btw

but it's a package

**Comment by tovade** [comment]
> > there's a thing called ts-node btw
> 
> but it's a package

npx ts-node 😘😘😘

**Comment by Polygons1** [comment]
> > > there's a thing called ts-node btw
> > 
> > 
> > but it's a package
> 
> npx ts-node 😘😘😘

but node is slow as 💩

**Comment by Polygons1** [comment]
just look in here, https://bun.sh

**Comment by tovade** [comment]
> just look in here, https://bun.sh

Not everyone is on linux....

**Comment by tovade** [comment]
Please use ts-node until bun.sh is fully working on windows

**Comment by Polygons1** [comment]
> Please use ts-node until bun.sh is fully working on windows

I made a bundled version that works 100% with node bruh (.mjs)

**Comment by Polygons1** [comment]
> > just look in here, https://bun.sh
> 
> Not everyone is on linux....

I gave you the URL to Bun just to see how much 💩 is node...

**Comment by Polygons1** [comment]
> > > > just look in here, https://bun.sh
> > > 
> > > 
> > > Not everyone is on linux....
> > 
> > 
> > I gave you the URL to Bun just to see how much 💩 is node...
> 
> No? I know bun.sh is fast but it doesn't mean nodejs is shit. I was just asking for a nodejs compatible version. I didn't ask for your fucking opinion on node

can node bundle files? can node install files without npm? can node use ESM and CommonJS in one project? short answer: NO.

**Comment by Polygons1** [comment]
Bun is all-in-one js runtime so it's 😎 and fast

**Comment by Polygons1** [comment]
> > > > just look in here, https://bun.sh
> > > 
> > > 
> > > Not everyone is on linux....
> > 
> > 
> > I gave you the URL to Bun just to see how much 💩 is node...
> 
> No? I know bun.sh is fast but it doesn't mean nodejs is shit. I was just asking for a nodejs compatible version. I didn't ask for your fucking opinion on node

btw bun can compile to node js files

**Comment by Polygons1** [comment]
> > > > > just look in here, https://bun.sh
> > > > 
> > > > 
> > > > Not everyone is on linux....
> > > 
> > > 
> > > I gave you the URL to Bun just to see how much 💩 is node...
> > 
> > 
> > No? I know bun.sh is fast but it doesn't mean nodejs is shit. I was just asking for a nodejs compatible version. I didn't ask for your fucking opinion on node
> 
> btw bun can compile to node js files

**Comment by Polygons1** [comment]
btw, here is what I said on the Discord:

it's bundled into a .mjs file
so that everyone can use
here is the command i used: bun build src/main.ts --outfile bussin.mjs --target node
.mjs because of ESM imports

**Comment by tovade** [comment]
make the BussinError class a seperate file so you can re-use it later :)

**Comment by tovade** [comment]
> > > > > just look in here, https://bun.sh
> > > > 
> > > > 
> > > > Not everyone is on linux....
> > > 
> > > 
> > > I gave you the URL to Bun just to see how much 💩 is node...
> > 
> > 
> > No? I know bun.sh is fast but it doesn't mean nodejs is shit. I was just asking for a nodejs compatible version. I didn't ask for your fucking opinion on node
> 
> can node bundle files? can node install files without npm? can node use ESM and CommonJS in one project? short answer: NO.

Once again, I DID NOT ASK FOR YOUR OPINION ON NODE PLEASE STOP GIVING YOUR OPINION GOD DAMN IT

**Comment by Polygons1** [comment]
oh hey @face-hh

**Comment by Polygons1** [comment]
> make the BussinError class a seperate file so you can re-use it later :)

thanks!

**Pull request closed without merging**
