### PR TITLE
Getter&setter for dynamic object keys, see execution time, fix local path for fs, add import(), add args, fix execution from other folders, more escaped characters in strings

### LINKED ISSUE #7: Regional currency symbol not following typographical norms for the euro symbol
https://github.com/face-hh/bussin/blob/6b2a504f73e5d5e685f6e92d8a59adc608ab49ea/README.md?plain=1#L46C38-L46C38

The correct way to use the euro sign would be: 
```rs
waffle(format("Hello, {}€", "World"))
```
Our competitors like DreamBerd already have this feature. So must we.

### LINKED ISSUE #49: Bussin cannot be run from other folders
If bussin is attempted to be ran from anywhere except main folder, it will say it can't find ./src/currencies.json

### PR DESCRIPTION
**Pull request by Symmettry**
fixes #7 
fixes #49

### CODE REVIEW

**Comment by Symmettry** [comment]
Wait i should be able to make transcriber no long async so it works with import()

**Comment by Symmettry** [comment]
aight done

**Comment by Symmettry** [comment]
Now fixes #7

**Comment by Symmettry** [comment]
Fixes #49 and includes \n now and stuff

**Comment by face-hh** [comment]
LGTM

**Pull request merged**
